package com.bpservice.webservicebanelco.resourse;

import com.bpservice.webservicebanelco.model.Banco;
import com.bpservice.webservicebanelco.repository.BancoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/banco") // This means URL's start with /banco (after Application path)
public class BancoResourse {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private BancoRepository bancoRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewBanco (@RequestParam String bancoNombre
            , @RequestParam String bancoCodigo) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Banco n = new Banco();
        n.setBancoNombre(bancoNombre);
        n.setBancoCodigo(bancoCodigo);
        bancoRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Banco> getAllBancos() {
        // This returns a JSON or XML with the users
        return bancoRepository.findAll();
    }
}

