package com.bpservice.webservicebanelco.resourse;
import com.bpservice.webservicebanelco.model.UsuarioMovimiento;
import com.bpservice.webservicebanelco.repository.UsrMovRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/usrMov") // This means URL's start with /usrMov (after Application path)
public class UsrMovResourse {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UsrMovRepository usrMovRepository;

    @PostMapping(path = "/add") // Map ONLY POST Requests
    public @ResponseBody
    String addNewUsuario(@RequestParam Integer idtipo
            , @RequestParam Integer idcuenta, @RequestParam Float monto,@RequestParam Integer cuentadestino) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        UsuarioMovimiento n = new UsuarioMovimiento();
        n.setIdCuenta(idcuenta);
        n.setIdTipo(idtipo);
        n.setIdCuentaDestino(cuentadestino);
        n.setMontoMov(monto);
        usrMovRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<UsuarioMovimiento> getAllUsuarios() {
        // This returns a JSON or XML with the users
        return usrMovRepository.findAll();
    }
}

