package com.bpservice.webservicebanelco.resourse;

import com.bpservice.webservicebanelco.model.Usuario;
import com.bpservice.webservicebanelco.repository.UsuarioRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/usuario") // This means URL's start with /usuario (after Application path)
public class UsuarioResourse {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UsuarioRepository usuarioRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUsuario (@RequestParam String nombre
            , @RequestParam String apellido,@RequestParam Integer cuit) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Usuario n = new Usuario();
        n.setApellido(apellido);
        n.setNombre(nombre);
        n.setCuit(cuit);
        usuarioRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Usuario> getAllUsuarios() {
        // This returns a JSON or XML with the users
        return usuarioRepository.findAll();
    }
}

